### ISSUE TITLE
Need to fix physics as fast as we can

### ISSUE THREAD

**Issue by alexlegoshin** [Khukhlaev/The_Mega_Yakut_Game#3]
Need to fix collisions. There are still too many bugs in there.
As going through the walls or accelerations when starting running near the wall.
Also after one of the last commits appeared such bug as going through the wall, when you are on the platform - this is new and too strange.
Also I've fallen under the platform after some kind of jump, I don't know...

The other thing is bad graphics of policeman, there are also some bugs. I'll try to fix them.
And we need to add normal hitboxes.

Appeared a critical error for me: error after closing the game. Like that:
invalid command name "16575544check_level_for_end"
    while executing
"16575544check_level_for_end"
    ("after" script)

So, we have to work...

**Comment by Khukhlaev** [comment]
We fix it, well done, team! You are the best!
