### ISSUE TITLE
Bug with falling under platform!

### ISSUE THREAD

**Issue by Khukhlaev** [Khukhlaev/The_Mega_Yakut_Game#4]
Need to fix it immediately! Now!

**Comment by Khukhlaev** [comment]
Steps to reproduce:
1. Run project. 
2. Push "right" when you near of platform on the right side.

**Comment by alexlegoshin** [comment]
I wanna sleep and I also wanna add AI, making normal enemies.
So I see this trouble as a fundametal.
Works for me.

**Comment by Khukhlaev** [comment]
OMG, bug now is eliminated, well done, my amazing team!
