### ISSUE TITLE
Need help to write AI.

### ISSUE THREAD

**Issue by alexlegoshin** [Khukhlaev/The_Mega_Yakut_Game#6]
By the end of the day I hope I'll import more graphics.
So I need some AI to work with it:
1) Dumb - just running from one to another side of platform
2) Medium - running and jumping from platform to platform
3) Static - just staying at one point. I hope it will shoot then.
4) Universal - running, jumping, staying, shooting - absolutely smart one.

**Comment by alexlegoshin** [comment]
And think please how to name everyone, I've written something untight with together.

**Comment by yaushevmikhail** [comment]
Ok, I'm going to write all the classes, but maybe without shooting yet.

**Comment by alexlegoshin** [comment]
project is cut. bust with ambition. the deadline was fcked

policeman + dog are enough, will write them until 23 pm
