### ISSUE TITLE
Player death animation must be fixed

### ISSUE THREAD

**Issue by alexlegoshin** [Khukhlaev/The_Mega_Yakut_Game#8]
I've written death animation, but as u can see it doesn't work
Need help to find a bug and fix it
Changes u can find in the last commit
The main, as I think, which added the problem and can help to solve it:
1) Added self.live in organism, which was used in ifs in level and player movement
2) Maybe smth from pushing on/under platform bugs the animation
3) Maybe some variable becoming 0 some time

**Comment by Khukhlaev** [comment]
FIXED!!!!!! Good job!
